// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI_LNrpZT9oCyicQKxnpLnMEO0lr0X-68',
    appId: '1:20204865581:web:cd0462de5686130298d0a4',
    messagingSenderId: '20204865581',
    projectId: 'my-first-firebase-project-2010',
    authDomain: 'my-first-firebase-project-2010.firebaseapp.com',
    storageBucket: 'my-first-firebase-project-2010.appspot.com',
    measurementId: 'G-ZZ3CVPWVWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHyrWFrN7gxE4-S0Ky7O9mDHSDcrztoM0',
    appId: '1:20204865581:android:6a1de05a4e335a4a98d0a4',
    messagingSenderId: '20204865581',
    projectId: 'my-first-firebase-project-2010',
    storageBucket: 'my-first-firebase-project-2010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZrHtjYCXsFn15mfJMknhKV5fiWJGzt8M',
    appId: '1:20204865581:ios:71aaef21e2f0f39898d0a4',
    messagingSenderId: '20204865581',
    projectId: 'my-first-firebase-project-2010',
    storageBucket: 'my-first-firebase-project-2010.appspot.com',
    iosClientId: '20204865581-o4oqv6rrq85dkac2cjbc5mp7124sei6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZrHtjYCXsFn15mfJMknhKV5fiWJGzt8M',
    appId: '1:20204865581:ios:71aaef21e2f0f39898d0a4',
    messagingSenderId: '20204865581',
    projectId: 'my-first-firebase-project-2010',
    storageBucket: 'my-first-firebase-project-2010.appspot.com',
    iosClientId: '20204865581-o4oqv6rrq85dkac2cjbc5mp7124sei6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample',
  );
}
